import type { Metadata } from "next";
import "@/common/scss/reset.scss";
import "@/common/scss/globals.scss";
import "@/common/scss/common.scss";
import "@/common/scss/map.scss";
import "@mantine/core/styles.css";

import { baseFont } from "src/features/font";
import { MantineProvider } from "@mantine/core";
import { theme } from "@/features/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head></head>
      <body className={baseFont.className}>
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
