import type { Metadata } from "next";
import "@/common/scss/reset.scss";
import "@/common/scss/globals.scss";
import "@/common/scss/common.scss";
import "@/common/scss/map.scss";
import { baseFont } from "src/features/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={baseFont.className}>{children}</body>
    </html>
  );
}
